name: Release

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotlight-windows-x64
          path: src-tauri/target/release/spotlight.exe

  build-macos-intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Install dependencies
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build -- --target x86_64-apple-darwin

      - name: Sign app
        run: codesign --force --deep --sign - src-tauri/target/x86_64-apple-darwin/release/bundle/macos/spotlight.app

      - name: Package app
        run: |
          cd src-tauri/target/x86_64-apple-darwin/release/bundle/macos
          zip -r spotlight-macos-intel.zip spotlight.app

      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotlight-macos-intel
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/macos/spotlight-macos-intel.zip

  build-macos-silicon:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install dependencies
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build -- --target aarch64-apple-darwin

      - name: Sign app
        run: codesign --force --deep --sign - src-tauri/target/aarch64-apple-darwin/release/bundle/macos/spotlight.app

      - name: Package app
        run: |
          cd src-tauri/target/aarch64-apple-darwin/release/bundle/macos
          zip -r spotlight-macos-silicon.zip spotlight.app

      - name: Upload macOS Silicon artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotlight-macos-apple-silicon
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/macos/spotlight-macos-silicon.zip

  create-release:
    needs: [build-windows, build-macos-intel, build-macos-silicon]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/spotlight-windows-x64/spotlight.exe
            artifacts/spotlight-macos-intel/spotlight-macos-intel.zip
            artifacts/spotlight-macos-apple-silicon/spotlight-macos-silicon.zip
          tag_name: v${{ github.run_number }}
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
